# Site
repository: isolino/isolino.github.io 
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Isolino G. Ferreira 
title: Android Developer
email: isolinogf@gmail.com
website: isolino.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: ferreiraiso
github_username: isolino 
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: isolino-ferreira
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/avatar.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Isolino and I'm a Android Developer. I started my career as a Java FullStack developer, so a migrated to android development and then starting learning Kotlin. Wich is my main programming language today.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: MyCalendar
        link: https://github.com/isolino/MyCalendar 
        # link_text: Project Website
        additional_links:
          - title:  isolino/MyCalendar
            icon: fab fa-github
            url: github.com/isolino/MyCalendar
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This app is the result of my efforts to learning and updating my knowledge in Android Development.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>Android/Kotlin</mark> and Prepare myself to google exams. It's follow the Archtecture Jetpack Compose specifications like Hilt, ViewModel, Pagination and so on.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vixteam Consultoria & Sistemas 
        link: http://vixteam.com.br
        # link_text: boringcompany.com
        sub_title: Java FullStack Developer
        caption: October 2016 - June 2018
        description: | # this will include new lines to allow paragraphs
            I worked developing and deploy systems for Petrobas. The technologies I used are Java, Hibernate, Spring, JSP and JavaScript.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Instituto Federal do Espírito Santo
        caption: 2010 - 2017
        sub_title: BSc Information Systems 
        quote: >
          Since its creation in 1909 as Escola de Aprendizes Artífices do Espírito Santo, the Instuto Federal do Espírito Santo is one of most respected institutes of the ES state.
        description: | # this will include new lines to allow paragraphs
          When in the IFES, I learned  how to solve problems using algorithms and how to develop systems integrated with database.

          In my Undergraduate Thesis, I used machining learning to identify the feeling expressed in a audio.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
